name: Evaluate
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    # optionally use a convenient Ubuntu LTS + CUDA + DVC + CML image
    # container: docker://dvcorg/cml:0-dvc2-base1-gpu
    steps:
      - uses: actions/checkout@v2
      # may need to setup NodeJS & Python3 on e.g. self-hosted
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: '12'
      - uses: actions/setup-python@v2
        with:
          python-version: '^3.9'
      - uses: iterative/setup-cml@v1
      - name: Install Poetry
        uses: snok/install-poetry@v1.1.6
      - name: Train model
        run: |
          # Your ML workflow goes here
          poetry install
          poetry run dvc repro
      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Post reports as comments in GitHub PRs
          git fetch --prune
          echo "## Params diff between this branch and master" >> report.md
          dvc params diff --show-md main > report.md
          cml-send-comment report.md
